# This is a basic workflow that is manually triggered

name: WEB TEAM PROD RELEASE APPROVAL

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment
jobs:
  # This workflow contains a single job called "greet"
  Test_API:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    continue-on-error: true
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v2      
    - run: echo RepoName=${{ github.event.repository.name }}
