name: New Repo & CICD Creation

on:
  workflow_dispatch:
    inputs:
      Repo-Name:
        description: Repository name which need to be created
        required: true
      name:
        type: choice
        description: API Type WEB or other
        required: true
        options: 
        - WEB-API
        - OTHER-API
      environment:
        type: choice
        description: prefix type PP or PREPROD
        required: true
        options: 
        - pp
        - preprod        
      message:
        required: true
      Branch-Protecion:
        type: boolean
        description: Branch protection requirement
      Env-Secrete:
        type: boolean
        description: Environment secrete configuration
      Repo-secrete:
        type: boolean
        description: repo-secrete configuration
         
jobs:
  # This workflow contains a single job called "greet"
  create-repo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    continue-on-error: true
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v2      
    - run: echo RepoName=${{ github.event.repository.name }}    
  Repo-sercet:   
   runs-on: ubuntu-latest
   steps:
    - uses: gliech/create-github-secret-action@v1
      with:
        location: horde-prime/spire-network
        name: BROADCAST_FREQUENCY
        value: ${{ secrets.JAMMING_FREQUENCY }}
        pa_token: ${{ secrets.PAT_WRONG_HORDAK }}
  repo-environments:
    runs-on: ubuntu-latest
    steps:
      - name: Create environments
        uses: thijsvtol/create-environments@main
        with:
          token: ${{ secrets.GHP }}
          repo: ${{ github.repository }}
          environments: test,prod
          required_reviewers: your-username
          wait_time: 5
          protected_branches_only: true 
  crete-env-sercret:
    runs-on: ubuntu-latest
    steps:
      - name: Create environments
        uses: thijsvtol/create-environments@main
        with:
          token: ${{ secrets.GHP }}
          repo: ${{ github.repository }}
          environments: test,prod
          required_reviewers: your-username
          wait_time: 5
          protected_branches_only: true     
